import type { Metadata } from "next";
import { Geist, Geist_Mono, Nova_Script } from "next/font/google";
import "./globals.css";

// Geist fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const novaScript = Nova_Script({
  weight: "400",           
  subsets: ["latin"],
  variable: "--font-magnolia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${novaScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}